name: "Deploy Cloud Functions"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v.4.1.2

      - name: Testes unitários
        run: |
          pip install pytest
          pytest . --verbose
